# Generated by Django 3.1.3 on 2021-03-01 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='booking_status_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
