# Generated by Django 3.1.3 on 2021-03-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_auto_20210301_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='partner_id',
            field=models.IntegerField(),
        ),
    ]
